baseURL: "https://yuchengzhou.com" 
title: Yucheng Zhou | Ph.D. Candidate in Finance
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Working Papers
          url: papers/
          weight: 2
        - name: Work in Progress
          url: wip/
          weight: 3
        - name: CV
          url: cv_yz.pdf
          weight: 4
        - name: Contact
          url: contact/
          weight: 6 
        - name: Teaching
          url: teaching/
          weight: 5 
        - name: News
          url: news/
          weight: 7


params:
    description: "Ph.D. Candidate in Finance at University of Illinois at Urbana-Champaign."
    author: Yucheng Zhou
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yucheng Zhou
          subtitle: "I am a Ph.D. Candidate in Finance at University of Illinois at Urbana-Champaign. My research focuses on **macro-finance**, **asset pricing** and **monetary policy**. My committee members are Heitor Almeida, Victor Duarte, Neil Pearson, Mathias Kronlund, and Yuchen Chen."
          imageUrl: "picture.jpg"
          imageWidth: 180
          imageHeight: 195
          buttons:
            - name: Job Market Paper
              url: jmp/
            - name: Research
              url: papers/
            - name: CV
              url: cv_yz.pdf
            - name: Contact
              url: contact/
            - name: News
              url: news/


    socialIcons:
        - name: CV
          url: cv_yz.pdf
        - name: Email
          url: mailto:yz33@illinois.edu
        - name: Google Scholar
          url: https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=5608307
        - name: GitHub
          url: https://github.com/YuchengZ-Fin
        - name: Twitter
          url: https://x.com/YuchengZhou99

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yucheng Zhou"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2